### PR TITLE
[Merged by Bors] - Add `/usr/share/drirc.d/00-mesa-defaults.conf`

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Another hard-coded path in libgl1-mesa-dri

### CODE REVIEW

**Review by wmww — APPROVED** [review]
LGTM
bors r+

**Comment by AlanGriffiths** [comment]
@wmww please let @RAOF have a say before landing this.

**Comment by wmww** [comment]
Ah, thanks. I missed that you requested review from him.

**Review by RAOF — APPROVED** [review]
This is sensible.

I'm still concerned that we're expecting `graphics-core20` users to add mesa-specific bits to their snapcraft metadata. Maybe we might want to try writing a snapcraft extension?

bors r+

**Pull request closed without merging**
